number = +prompt('enter number')

alert(number)
alert(number + 1)
alert(number + 2)
alert(number + 3)
alert(number + 4)
alert(number + 5)
alert(number + 6)
alert(number + 7)
alert(number + 8)
alert(number + 9)
alert(number + 10)
alert(number + 11)
alert(number + 12)
alert(number + 13)
alert(number + 14)
alert(number + 15)
alert(number + 16)
alert(number + 17)
