# this file will essentially describe all the "docker run" commands that
# are required in order to launch a system that is combined of 
# several images to the air

# each service ends up as a docker container
# that is, each service translates to a docker run command
services:
  # docker run --name betterx-db -e=MYSQL_ALLOW_EMPTY_PASSWORD=1 -e=MYSQL_DATABASE=college -e=MYSQL_TCP_PORT=3306 -p 3306:3306 -d shaharsol/betterx-db:1.0
  database:
    container_name: betterx-db-compose
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=college
      - MYSQL_TCP_PORT=3306
    ports:
      - 3306:3306
    # i can either use an existing image
    # this means i need to commit that an image will actually be in the hub
    # image: shaharsol/betterx-db:1.0
    # which is not always the case, especially during development period
    # so i can assume the code exists in the client machine
    # (they did git clone, they are after all other developers or devops 
    # from my organization)
    # so i can instruct how to build an image ad hoc:
    # which is actually the location of a Dockerfile
    build: ./database
      

  #localstack:
  #io:
  #backend:
  #frontend:
