# this file will essentially describe all the "docker run" commands that
# are required in order to launch a system that is combined of 
# several images to the air

# each service ends up as a docker container
# that is, each service translates to a docker run command
services:
  # docker run --name betterx-db -e=MYSQL_ALLOW_EMPTY_PASSWORD=1 -e=MYSQL_DATABASE=college -e=MYSQL_TCP_PORT=3306 -p 3306:3306 -d shaharsol/betterx-db:1.0
  database:
    container_name: betterx-db-compose
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=college
      - MYSQL_TCP_PORT=3306
    expose:
      - 3306
    # ports:
    #   - 3306:3306
    # i can either use an existing image
    # this means i need to commit that an image will actually be in the hub
    # image: shaharsol/betterx-db:1.0
    # which is not always the case, especially during development period
    # so i can assume the code exists in the client machine
    # (they did git clone, they are after all other developers or devops 
    # from my organization)
    # so i can instruct how to build an image ad hoc:
    # which is actually the location of a Dockerfile
    build: ./database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
      
  # docker run --name localstack -d -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack:4.4.0
  localstack:
    container_name: localstack-compose
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    image: localstack/localstack:4.4.0

  # docker run -d --name pgvector --platform linux/amd64 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 pgvector/pgvector:pg16
  pgvector:
    container_name: pgvector-compose
    platform: linux/amd64
    build: ./pgvector
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # docker run --name betterx-io -p 3004:3004 -d shaharsol/betterx-io:2.2
  io:
    container_name: betterx-io-compose
    ports:
      - 3004:3004
    build: ./io

  # docker run --name betterx-backend-p 3000:3000 -e BETTERX_OPENAI_API_KEY=sk-proj-1234567890 -d shaharsol/betterx-backend:3.0
  backend:
    container_name: betterx-backend-compose
    ports:
      - 3000:3000
    environment:
      - BETTERX_OPENAI_API_KEY=${BETTERX_OPENAI_API_KEY}
    build:
      context: ./backend
      dockerfile: Dockerfile.compose
    depends_on:
      database:
        condition: service_healthy
  
  # docker run --name betterx-front -p 6123:80 -d shaharsol/betterx-front:2.0
  frontend:
    container_name: betterx-front-compose
    ports:
      - 6123:80
    build: ./frontend

volumes:
  pgvector-data:
